<?php
/**
 * DefaultApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * eHelply SDK - 1.1.82
 *
 * eHelply SDK for SuperStack Services
 *
 * The version of the OpenAPI document: 1.1.82
 * Contact: support@ehelply.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.0.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client\Test\Api;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * DefaultApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class DefaultApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for attachEntityToAppointment
     *
     * Attach Entity To Appointment.
     *
     */
    public function testAttachEntityToAppointment()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for attachProductToCatalog
     *
     * Attach Product To Catalog.
     *
     */
    public function testAttachProductToCatalog()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createAppointment
     *
     * Create Appointment.
     *
     */
    public function testCreateAppointment()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createCatalog
     *
     * Create Catalog.
     *
     */
    public function testCreateCatalog()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createProduct
     *
     * Create Product.
     *
     */
    public function testCreateProduct()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createReview
     *
     * Create Review.
     *
     */
    public function testCreateReview()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteAppointment
     *
     * Delete Appointment.
     *
     */
    public function testDeleteAppointment()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteCatalog
     *
     * Delete Catalog.
     *
     */
    public function testDeleteCatalog()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteProduct
     *
     * Delete Product.
     *
     */
    public function testDeleteProduct()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteReview
     *
     * Delete Review.
     *
     */
    public function testDeleteReview()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for detachEntityFromAppointment
     *
     * Detach Entity From Appointment.
     *
     */
    public function testDetachEntityFromAppointment()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for detachProductFromCatalog
     *
     * Detach Product From Catalog.
     *
     */
    public function testDetachProductFromCatalog()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getAppointment
     *
     * Get Appointment.
     *
     */
    public function testGetAppointment()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getCatalog
     *
     * Get Catalog.
     *
     */
    public function testGetCatalog()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getProduct
     *
     * Get Product.
     *
     */
    public function testGetProduct()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getReview
     *
     * Get Review.
     *
     */
    public function testGetReview()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for searchAppointment
     *
     * Search Appointment.
     *
     */
    public function testSearchAppointment()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for searchAppointmentEntities
     *
     * Search Appointment Entities.
     *
     */
    public function testSearchAppointmentEntities()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for searchCatalogProducts
     *
     * Search Catalog Products.
     *
     */
    public function testSearchCatalogProducts()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for searchCatalogs
     *
     * Search Catalogs.
     *
     */
    public function testSearchCatalogs()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for searchEntityAppointments
     *
     * Get Entities Appointments.
     *
     */
    public function testSearchEntityAppointments()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for searchProduct
     *
     * Search Products.
     *
     */
    public function testSearchProduct()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for searchProductCatalog
     *
     * Search Product Catalogs.
     *
     */
    public function testSearchProductCatalog()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for searchReviews
     *
     * Search Review.
     *
     */
    public function testSearchReviews()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateAppointment
     *
     * Update Appointment.
     *
     */
    public function testUpdateAppointment()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateCatalog
     *
     * Update Catalog.
     *
     */
    public function testUpdateCatalog()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateProduct
     *
     * Update Product.
     *
     */
    public function testUpdateProduct()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateReview
     *
     * Update Review.
     *
     */
    public function testUpdateReview()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
