<?php
/**
 * PlacesApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * eHelply SDK - 1.1.93
 *
 * eHelply SDK for SuperStack Services
 *
 * The version of the OpenAPI document: 1.1.93
 * Contact: support@ehelply.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.1.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client\Test\Api;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * PlacesApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class PlacesApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for createPlacePlacesPlacesPost
     *
     * Create Place.
     *
     */
    public function testCreatePlacePlacesPlacesPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deletePlacePlacesPlacesPlaceUuidDelete
     *
     * Delete Place.
     *
     */
    public function testDeletePlacePlacesPlacesPlaceUuidDelete()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for forwardGeocodingPlacesGeocodingForwardGet
     *
     * Forward Geocoding.
     *
     */
    public function testForwardGeocodingPlacesGeocodingForwardGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getPlacePlacesPlacesPlaceUuidGet
     *
     * Get Place.
     *
     */
    public function testGetPlacePlacesPlacesPlaceUuidGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for reverseGeocodingPlacesGeocodingReverseGet
     *
     * Reverse Geocoding.
     *
     */
    public function testReverseGeocodingPlacesGeocodingReverseGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for searchPlacesBySearchStringPlacesSearchPlacesStringGet
     *
     * Search Places By Search String.
     *
     */
    public function testSearchPlacesBySearchStringPlacesSearchPlacesStringGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for searchPlacesPlacesPlacesGet
     *
     * Search Places.
     *
     */
    public function testSearchPlacesPlacesPlacesGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updatePlacePlacesPlacesPlaceUuidPut
     *
     * Update Place.
     *
     */
    public function testUpdatePlacePlacesPlacesPlaceUuidPut()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
