<?php
/**
 * ProjectsApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * eHelply SDK - 1.1.95
 *
 * eHelply SDK for SuperStack Services
 *
 * The version of the OpenAPI document: 1.1.95
 * Contact: support@ehelply.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.1.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client\Test\Api;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * ProjectsApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ProjectsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for addMemberToProject
     *
     * Addmembertoproject.
     *
     */
    public function testAddMemberToProject()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for archiveProject
     *
     * Archiveproject.
     *
     */
    public function testArchiveProject()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createProject
     *
     * Createproject.
     *
     */
    public function testCreateProject()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createProjectKey
     *
     * Createprojectkey.
     *
     */
    public function testCreateProjectKey()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createUsageType
     *
     * Createusagetype.
     *
     */
    public function testCreateUsageType()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteProjectKey
     *
     * Deleteprojectkey.
     *
     */
    public function testDeleteProjectKey()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteUsageType
     *
     * Deleteusagetype.
     *
     */
    public function testDeleteUsageType()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getAllProjectUsage
     *
     * Getallprojectusage.
     *
     */
    public function testGetAllProjectUsage()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getMemberProjects
     *
     * Getmemberprojects.
     *
     */
    public function testGetMemberProjects()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getProject
     *
     * Getproject.
     *
     */
    public function testGetProject()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getProjectKeys
     *
     * Getprojectkeys.
     *
     */
    public function testGetProjectKeys()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getProjectMembers
     *
     * Getprojectmembers.
     *
     */
    public function testGetProjectMembers()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getSpecificProjectUsage
     *
     * Getspecificprojectusage.
     *
     */
    public function testGetSpecificProjectUsage()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getUsageType
     *
     * Getusagetype.
     *
     */
    public function testGetUsageType()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for removeMemberFromProject
     *
     * Removememberfromproject.
     *
     */
    public function testRemoveMemberFromProject()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for searchProjects
     *
     * Searchprojects.
     *
     */
    public function testSearchProjects()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for searchUsageType
     *
     * Searchusagetype.
     *
     */
    public function testSearchUsageType()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateProject
     *
     * Updateproject.
     *
     */
    public function testUpdateProject()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateUsageType
     *
     * Updateusagetype.
     *
     */
    public function testUpdateUsageType()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
